In [1]:
import numpy as np
import pandas as pd

In [2]:
ds = pd.read_csv(r"C:\Users\vamsh\Downloads\bank.csv")

In [3]:
ds.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [4]:
ds.drop("job",axis=1,inplace=True)

In [5]:
ds.head(1)

age  marital  education default  balance housing loan  contact  day month  \
0   59  married  secondary      no     2343     yes   no  unknown    5   may   

   duration  campaign  pdays  previous poutcome deposit  
0      1042         1     -1         0  unknown     yes

In [6]:
ds.drop("marital",axis=1,inplace=True)

In [7]:
ds.drop("default",axis=1,inplace=True)

In [8]:
ds.drop("month",axis=1,inplace=True)

In [9]:
ds.drop("poutcome",axis=1,inplace=True)

In [10]:
ds.head(1)

age  education  balance housing loan  contact  day  duration  campaign  \
0   59  secondary     2343     yes   no  unknown    5      1042         1   

   pdays  previous deposit  
0     -1         0     yes

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
ds["contact"] = le.fit_transform(ds["contact"])
ds["housing"] = le.fit_transform(ds["housing"])
ds["deposit"] = le.fit_transform(ds["deposit"])
ds["education"] = le.fit_transform(ds["education"])
ds["loan"] = le.fit_transform(ds["loan"])

In [28]:
ds.head()

age  education  balance  housing  loan  contact  day  duration  campaign  \
0   59          1     2343        1     0        2    5      1042         1   
1   56          1       45        0     0        2    5      1467         1   
2   41          1     1270        1     0        2    5      1389         1   
3   55          1     2476        1     0        2    5       579         1   
4   54          2      184        0     0        2    5       673         2   

   pdays  previous  deposit  
0     -1         0        1  
1     -1         0        1  
2     -1         0        1  
3     -1         0        1  
4     -1         0        1

In [34]:
ds.head(1)

age  education  balance  housing  loan  contact  day  duration  campaign  \
0   59          1     2343        1     0        2    5      1042         1   

   pdays  previous  deposit  
0     -1         0        1

In [35]:
x = ds.iloc[:,0:11].values
y = ds.iloc[:,11].values


In [36]:
x

array([[  59,    1, 2343, ...,    1,   -1,    0],
       [  56,    1,   45, ...,    1,   -1,    0],
       [  41,    1, 1270, ...,    1,   -1,    0],
       ...,
       [  32,    1,   29, ...,    2,   -1,    0],
       [  43,    1,    0, ...,    2,  172,    5],
       [  34,    1,    0, ...,    1,   -1,    0]], dtype=int64)

In [37]:
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

In [38]:
x.shape

(11162, 11)

In [47]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 10000)

In [48]:
x_train

array([[ 59,   2,  59, ...,   1,  -1,   0],
       [ 44,   1, 608, ...,  30,  -1,   0],
       [ 26,   1, 237, ...,   3,  -1,   0],
       ...,
       [ 52,   1, 105, ...,   4,  -1,   0],
       [ 54,   1,  83, ...,   3,  -1,   0],
       [ 48,   1, 558, ...,   8,  -1,   0]], dtype=int64)

In [49]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [50]:
x_train

array([[ 1.49983846,  0.96411175, -0.45261061, ..., -0.56446046,
        -0.47466251, -0.35339114],
       [ 0.23948068, -0.37553248, -0.28422509, ..., 10.21603495,
        -0.47466251, -0.35339114],
       [-1.27294865, -0.37553248, -0.39801567, ...,  0.17902198,
        -0.47466251, -0.35339114],
       ...,
       [ 0.9116715 , -0.37553248, -0.43850181, ...,  0.5507632 ,
        -0.47466251, -0.35339114],
       [ 1.0797192 , -0.37553248, -0.4452495 , ...,  0.17902198,
        -0.47466251, -0.35339114],
       [ 0.57557609, -0.37553248, -0.29956075, ...,  2.03772808,
        -0.47466251, -0.35339114]])

In [51]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression ()
logreg.fit(x_train,y_train)

C:\Users\vamsh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [52]:
ypred = logreg.predict(x_test)
ypred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [53]:
y_test

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [54]:
from sklearn.metrics import accuracy_score
acc = accuracy_score(ypred,y_test)
acc

0.7962382445141066

In [55]:
ds.head(1)

age  education  balance  housing  loan  contact  day  duration  campaign  \
0   59          1     2343        1     0        2    5      1042         1   

   pdays  previous  deposit  
0     -1         0        1

In [56]:
logreg.predict([[19,2,134,0,1,0,4,1000,0,2,1]])

array([1], dtype=int64)